name = "hutech-tech"
compatibility_date = "2026-02-28"
workers_dev = true

routes = [
  { pattern = "hutech.tech/*", zone_name = "hutech.tech" },
  { pattern = "www.hutech.tech/*", zone_name = "hutech.tech" }
]

[assets]
directory = "."
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"
